require: rubocop-rspec
inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'config/initializers/devise.rb'
    - 'config/initializers/simple_form*'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'features/step_definitions/email_steps.rb'
  RunRailsCops: true
Metrics/LineLength:
  Max: 120
Style/SingleSpaceBeforeFirstArg:
  Enabled: false
Style/Documentation:
  Enabled: false

